name: dart_code_metrics
version: 5.7.6
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev/
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/getting-started/

environment:
  sdk: ">=3.0.0"

dependencies:
  analyzer: ^5.13.0
  analyzer_plugin: ^0.11.2
  ansicolor: ^2.0.1
  args: ^2.4.2
  collection: ^1.18.0
  crypto: ^3.0.3
  dart_code_metrics_presets: ^2.4.0
  file: ^6.1.4
  glob: ^2.1.2
  html: ^0.15.4
  http: ^1.1.0
  meta: ^1.9.1
  path: ^1.8.3
  platform: ^3.1.1
  pub_updater: ^0.3.1
  source_span: ^1.10.0
  uuid: ^3.0.7
  xml: ^6.3.0
  yaml: ^3.1.2

dev_dependencies:
  coverage: ^1.6.4
  intl: ^0.18.1
  lints: ^2.1.1
  mocktail: ^1.0.1
  test: ^1.24.7

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
