name: dart_code_metrics
version: 5.8.0+1
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev/
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/getting-started/

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: any
  analyzer_plugin: any
  ansicolor: any
  args: any
  collection: any
  crypto: any
  dart_code_metrics_presets: any
  file: any
  glob: any
  html: any
  http: any
  meta: any
  path: any
  platform: any
  pub_updater: any
  source_span: any
  uuid: any
  xml: any
  yaml: any

dev_dependencies:
  coverage: ^1.7.2
  intl: ^0.19.0
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.25.4

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
